### ISSUE TITLE
💅 [Design]: 로그인 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by dananote** [haron-lee/we-wear-weather#1]
## Description
로그인 페이지 마크업 및 스타일링 

## To-do
- [x] 성별/ 나이 컴포넌트 생성
- [x] 사용하는 이미지 에셋 추가
- [x] 버튼 컴포넌트 생성
