### ISSUE TITLE
🛠️ [Feature]:  Login Page 기능구현

### ISSUE THREAD

**Issue by dananote** [haron-lee/we-wear-weather#24]
## Description
유저가 선택한 정보를 저장하고 성공적으로 저장되면 메인페이지로 이동

## To-do
- [ ] 유저가 선택한 성별, 나이 recoil에서 전역관리
- [ ] 유저가 선택하지 않았을시 에러알럿창
- [ ] 성공적으로 저장시 메인페이지로 이동

## 전달사항
{gender: string, age: strting} 객체로 저장
