### ISSUE TITLE
🛠️ [Feature]: 주간예보

### ISSUE THREAD

**Issue by haron-lee** [haron-lee/we-wear-weather#30]
## Description
주간예보 기능넣기

## To-do
- [x] 주간예보 API useOpenWeatherAPI에 추가
- [x] 주간예보 API 데이터 뿌려주기 
- [x] 재사용 type 분리 
- [x] 날짜포맷 변경 함수 생성 (로직분리)
- [x] 최저 및 최고 필터링 함수 생성 (로직분리)

## 기타사항
- [x] index.html 로고 상시에러 수정
- [x] active 상시 에러 수정
- [x] Home에서 Forecast 오타 수정
