### ISSUE TITLE
💅 [Design]: 미세먼지, 시간대별 날씨, 캐릭터 

### ISSUE THREAD

**Issue by haron-lee** [haron-lee/we-wear-weather#5]
## Description
미세먼지 UI, 시간대별 날씨

## To-do
- [x] 미세먼지  컴포넌트 생성
- [x] 시간대별 날씨  컴포넌트 생성
- [x] 캐릭터 UI 생성
- [x] 캐릭터 모달 생성
