### ISSUE TITLE
👾 [Bug]: 시간대별 에러 수정, 주간날씨 UI 수정, 자잘한 UI 수정

### ISSUE THREAD

**Issue by haron-lee** [haron-lee/we-wear-weather#50]
## Description
에러수정하기

## To-do
- [x] 오늘일 때 최저 | 최고가 ui가 밀림
- [x] 시간대별 날씨 이틀 안쪽으로 자르기
- [x] 메인 레이아웃 overflow: auto;
- [x] 바텀네비 z-index:20;
- [x] 시간대별 날씨 이전날짜 데이터가 그대로 있는 것 에러 수정
    - 데이터가 계속 빠르게 업데이트 되지 않아서 그럼
- [x] 주간날씨 날짜바꿔주는 chnageDate 함수내에서 이전날짜 필터링해주기
