### ISSUE TITLE
♻️ [Refactor]: 카드 위젯 버그 수정

### ISSUE THREAD

**Issue by dananote** [haron-lee/we-wear-weather#60]
## Description
카드 위젯 버그및  어류 수정

## To-do
- [ ] description ‘입니다’ 제거
- [ ] 카드 small icon description에 맞춰서 대응
- [ ] 카드 비오는 날씨 애니메이션 작동 버그 수정
